language: java
jdk:
  - openjdk9

script:
  - mvn jacoco:prepare-agent test

after_success:
  - mvn prepare-package -DskipTests=true
  - mvn jacoco:report coveralls:report

cache:
  directories:
  - $HOME/.m2